version: '3.8'

services:
  openhab:
    image: openhab/openhab:latest
    ports:
      - "18080:8080"
    environment:
      - OPENHAB_HTTP_PORT=8080
      - EXTRA_JAVA_OPTS=-Duser.timezone=UTC
    volumes:
      - ./docker/openhab/conf:/openhab/conf
      - ./docker/openhab/userdata:/openhab/userdata
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/rest"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - openhab-network

  openhab-mcp:
    build: .
    ports:
      - "8081:8080"  # Changed to 8081 to avoid conflict with OpenHAB
    environment:
      - OPENHAB_URL=http://openhab:8080
      - OPENHAB_API_TOKEN=${OPENHAB_API_TOKEN:-}
      - OPENHAB_USERNAME=${OPENHAB_USERNAME:-}
      - OPENHAB_PASSWORD=${OPENHAB_PASSWORD:-}
    depends_on:
      openhab:
        condition: service_healthy
    networks:
      - openhab-network

networks:
  openhab-network:
    driver: bridge
