version: '3.8'

services:
  openhab-mcp:
    build: .
    container_name: openhab-mcp
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - OPENHAB_URL=${OPENHAB_URL:-http://openhab:8080}
      - OPENHAB_API_TOKEN=${OPENHAB_API_TOKEN:-}
      - OPENHAB_USERNAME=${OPENHAB_USERNAME:-}
      - OPENHAB_PASSWORD=${OPENHAB_PASSWORD:-}
      - LOG_LEVEL=INFO
    volumes:
      - ./process_template_override:/app/process_templates/override
    networks:
      - openhab-network

networks:
  openhab-network:
    driver: bridge
    name: openhab-network
