version: '3.8'

services:
  openhab-mcp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: openhab-mcp
    restart: unless-stopped
    ports:
      - "8081:8000"
    # Environment variables are loaded from .env file in the docker directory
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../openhab_mcp/process_templates/override:/app/openhab_mcp/process_templates/override
    networks:
      - openhab-network

networks:
  openhab-network:
    driver: bridge
    name: openhab-network